WITH TopReview AS (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS reviewCNT
     FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY reviewCNT DESC
    LIMIT 1
) 
SELECT A.MEMBER_NAME, C.REVIEW_TEXT
        , DATE_FORMAT(C.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
INNER JOIN TopReview B
ON A.MEMBER_ID = B.MEMBER_ID
INNER JOIN REST_REVIEW C
ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY C.REVIEW_DATE, C.REVIEW_TEXT


SET @MEMBER_ID := (SELECT MEMBER_ID
                     FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(MEMBER_ID) DESC
                    LIMIT 1);

SELECT T1.MEMBER_NAME, T2.REVIEW_TEXT, SUBSTR(T2.REVIEW_DATE, 1, 10) AS REVIEW_DATE
  FROM MEMBER_PROFILE T1
       INNER JOIN REST_REVIEW T2
          ON T2.MEMBER_ID = T1.MEMBER_ID
 WHERE T1.MEMBER_ID = @MEMBER_ID
 ORDER BY REVIEW_DATE, REVIEW_TEXT