WITH TopReview AS (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS reviewCNT
     FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY reviewCNT DESC
    LIMIT 1
) 
SELECT A.MEMBER_NAME, C.REVIEW_TEXT
        , DATE_FORMAT(C.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
INNER JOIN TopReview B
ON A.MEMBER_ID = B.MEMBER_ID
INNER JOIN REST_REVIEW C
ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY C.REVIEW_DATE, C.REVIEW_TEXT